export {
  addAdminInstance,
  addCookieAccount,
  collectInstanceHealth,
  connectMongo,
  CookiePoolError,
  createWatchRoom,
  deleteAdminInstance,
  deleteCookieAccount,
  GoogleAccount,
  Instance,
  InstanceClient,
  InstanceError,
  InstancePoolError,
  isRotatableInstanceErrorCode,
  listCookieAccounts,
  listInstances,
  markCookieAccountAutoDisabled,
  parseInstancesJson,
  pingInstance,
  previewVideo,
  Room,
  selectStreamingInstance,
  setCookieAccountDisabled,
  setInstanceEnabled,
  startInstanceHealthLoop,
  syncInstancesFromEnv,
  WatchPartyError,
  withCookieRotation,
  type AddCookiesInput,
  type CookieRecordView,
  type GoogleAccountDoc,
  type GoogleAccountModel,
  type HealthLoopOptions,
  type HealthSummary,
  type EnvInstance,
  type InstanceCookie,
  type InstanceDoc,
  type InstanceErrorCode,
  type InstanceFormat,
  type InstanceHealth,
  type InstanceInfo,
  type InstanceModel,
  type InstanceRecordView,
  type InstanceTarget,
  type RoomVideoFormat,
  type StreamRequest,
  type SyncReport,
  type YtDlpCredentials,
} from "@wave/shared";
