// Package cookies writes a JSON-array cookie payload from the master node into
// a Netscape-format cookies.txt file that yt-dlp can consume via --cookies.
//
// The file is created with mode 0600 in the OS temp dir and must be removed
// by the caller (typically with defer File.Remove()).
package cookies

import (
	"errors"
	"fmt"
	"os"
	"strings"
)

// Cookie is the wire format the master sends in request bodies. Names match
// the [Chrome DevTools Protocol] / Playwright cookie shape so the master can
// pass through whatever the user uploaded in the admin panel.
//
// [Chrome DevTools Protocol]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Cookie
type Cookie struct {
	Name     string  `json:"name"`
	Value    string  `json:"value"`
	Domain   string  `json:"domain"`
	Path     string  `json:"path"`
	Expires  float64 `json:"expires,omitempty"` // unix seconds, 0 ⇒ session
	HTTPOnly bool    `json:"httpOnly,omitempty"`
	Secure   bool    `json:"secure,omitempty"`
	SameSite string  `json:"sameSite,omitempty"` // unused in Netscape, kept for parity
}

// File wraps a temp file and deletes it on Remove.
type File struct {
	Path string
}

// Remove deletes the underlying file, ignoring not-exist errors.
func (f *File) Remove() {
	if f == nil || f.Path == "" {
		return
	}
	_ = os.Remove(f.Path)
}

// Write serialises cookies to a Netscape file in the OS temp dir. Returns nil,
// nil when the input is empty so callers can skip the --cookies flag.
//
// Netscape cookie format reference: each line has 7 tab-separated fields:
//
//	<domain> <flag> <path> <secure> <expiration> <name> <value>
//
// where <flag> is "TRUE" if the cookie applies to subdomains (domain starts
// with a leading dot), and <secure> is "TRUE"/"FALSE".
func Write(cookies []Cookie) (*File, error) {
	if len(cookies) == 0 {
		return nil, nil
	}

	var b strings.Builder
	b.WriteString("# Netscape HTTP Cookie File\n")
	b.WriteString("# Generated by wave-instance — do not edit\n")
	for _, c := range cookies {
		if err := validate(c); err != nil {
			return nil, err
		}
		domain := c.Domain
		flag := "FALSE"
		if strings.HasPrefix(domain, ".") {
			flag = "TRUE"
		}
		secure := "FALSE"
		if c.Secure {
			secure = "TRUE"
		}
		expires := int64(c.Expires)
		fmt.Fprintf(&b, "%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
			domain, flag, defaultIfEmpty(c.Path, "/"), secure, expires, c.Name, c.Value)
	}

	f, err := os.CreateTemp("", "wave-cookies-*.txt")
	if err != nil {
		return nil, fmt.Errorf("create temp cookies file: %w", err)
	}
	if err := os.Chmod(f.Name(), 0o600); err != nil {
		_ = os.Remove(f.Name())
		return nil, fmt.Errorf("chmod cookies file: %w", err)
	}
	if _, err := f.WriteString(b.String()); err != nil {
		_ = f.Close()
		_ = os.Remove(f.Name())
		return nil, fmt.Errorf("write cookies file: %w", err)
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(f.Name())
		return nil, fmt.Errorf("close cookies file: %w", err)
	}
	return &File{Path: f.Name()}, nil
}

func validate(c Cookie) error {
	if c.Name == "" {
		return errors.New("cookie missing name")
	}
	if c.Domain == "" {
		return errors.New("cookie missing domain")
	}
	// Reject any cookie that would corrupt the Netscape file (tabs/newlines).
	for _, s := range []string{c.Name, c.Value, c.Domain, c.Path} {
		if strings.ContainsAny(s, "\t\n\r") {
			return fmt.Errorf("cookie field contains forbidden whitespace: %q", s)
		}
	}
	return nil
}

func defaultIfEmpty(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
